### ISSUE TITLE
`STORAGE_ENABLED` env variable is ignored

### ISSUE THREAD

**Issue by Marcisbee** [nhost/hasura-backend-plus#621] opened 2021-07-11 08:35 UTC
Is this correct logic?
https://github.com/nhost/hasura-backend-plus/blob/master/src/shared/config/storage.ts#L8

By the looks of it, it seems that if user is set:

`STORAGE_ENABLED` as `false` and/or `STORAGE_ENABLE` as `false`

then `STORAGE.ENABLED` will always be `true` no matter what. Basically ignoring whatever user is entered.

**Comment by plmercereau** [comment] 2021-07-11 09:28
duplicate of #609

**Comment by elitan** [comment] 2021-07-13 10:54
Fixed in https://github.com/nhost/hasura-backend-plus/commit/b685de451bc7aefb19de6b19f5323855bd8bc1e6

**Closed** 2021-07-13 10:54 UTC
