### ISSUE TITLE
Catching unique REGISTRATION_CUSTOM_FIELDS

### ISSUE THREAD

**Issue by joshmedeski** [nhost/hasura-backend-plus#593] opened 2021-06-15 16:19 UTC
I'm building an app that uses the `username` custom registration field. I've added a unique constraint on the database but get a general 500 if that unique constraint fails.

```
hasura-backend-plus_1  | Error inserting user account
hasura-backend-plus_1  | Error: Could not perform request
hasura-backend-plus_1  |     at Object.request (/app/dist/shared/request.js:25:15)
hasura-backend-plus_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
hasura-backend-plus_1  |     at async registerAccount (/app/dist/routes/auth/register.js:50:20)
```

I'd like to hasura-backend-plus to return an appropriate message like this:

> username is already taken

**Comment by joshmedeski** [comment] 2021-06-15 16:22
@elitan @komninoschat let me know if you have any suggestions on how to code this. I'm thinking of allowing any unique constraint errors to output an appropriate error message like this:

```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "username already exists."
}
```

**Comment by elitan** [comment] 2021-07-14 14:58
Duplicate of https://github.com/nhost/hasura-backend-plus/issues/426

The server will return 500 and logs will be available for HBP.

**Closed by elitan** 2021-07-14 14:58 UTC
