### ISSUE TITLE
Delete user only deletes account

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#499] opened 2021-04-26 13:48 UTC
The `auth/delete` route that allows users to delete themselves only removes the account in the `auth.accounts` table.

Instead, it should delete the user in the `users` table that in turn, using [cascade](https://github.com/nhost/hasura-backend-plus/blob/master/migrations/1_init/up.sql#L108), will delete the `auth.accounts` record.

For reference:
https://github.com/nhost/hasura-backend-plus/blob/master/src/routes/auth/delete.ts#L20
https://github.com/nhost/hasura-backend-plus/blob/master/src/shared/queries.ts#L249

**Comment by plmercereau** [comment] 2021-04-26 13:55
Not sure of that. Public schema is supposed to be independent from HBP and
should not be altered if HBP is removed

**Comment by nunopato** [comment] 2021-04-26 13:57
@plmercereau that's the thing, it isn't independent. The `users` table is created by HBP on the `public` schema. What do you think about moving `users` into `auth` as well?

**Comment by plmercereau** [comment] 2021-04-26 14:04
The idea of the account/user split is to have a user table that can be specific to any application e.g. columns that are not related to hbp

**Comment by elitan** [comment] 2021-04-26 14:05
The `users` table is already too integrated into HBP I think. If you remove the `users` table HBP stops working for example.

**Comment by plmercereau** [comment] 2021-04-26 14:08
The problem is, what about other cascading constraints in public.user?
If another public table depends on the user table, then user deletion will either fail or be cascaded in a possible unexpected way.

**Comment by plmercereau** [comment] 2021-04-26 14:10
I would avoid merging both tables as developers would inevitably end up adding their own custom fields in the auth schema.

It is however possible to consider an optional cascade in an env var (yeyyyy another env var)

**Comment by elitan** [comment] 2021-04-26 14:11
I think that's fine. If people set `ON DELETE CASADE` that's what will happen. If not, and the `auth/delete` fails we'll error out that.

Also related: https://github.com/nhost/hasura-backend-plus/issues/153#issuecomment-613702560

**Comment by nunopato** [comment] 2021-04-26 14:21
> The idea of the account/user split is to have a user table that can be specific to any application e.g. columns that are not related to hbp

I like that separation and giving users "a place" to have custom columns. Do you think better docs explaining that new data on a user should be done with a new table referencing users? This way we could move to auth (or merge with accounts).

> Wouldn't that be OK?

I think we want to avoid changes from users to our own tables that are not in the `public` schema.

**Comment by komninoschat** [comment] 2021-05-03 12:44
Will be fixed by #153.

**Closed by komninoschat** 2021-05-03 12:44 UTC
Labels: Priority: Critical, Scope: Authentication, Status: Research Needed, Type: Bug
