### ISSUE TITLE
[next] anonymous login

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#212] opened 2020-05-04 15:15 UTC
Firebase-like, following Discord discussion.
However there may be a confusion between an anonymous user e.g. the user that gets a JWT without being registered, so they can register later and keep their previous data, and the Hasura anonymous role that allows some operations without sending any jwt. Both are valid and they should be usable together.
We may want to use a distinct name to the Hasura anonymous concept, maybe `unregistered`?

**Comment by elitan** [comment] 2020-07-28 07:40
I think we should keep calling it `anonymous`. We have [`is_anonymous` already in the `auth.accounts` table](https://github.com/nhost/hasura-backend-plus/blob/master/migrations/1_init/up.sql#L40) and the [`anonymous` role added](https://github.com/nhost/hasura-backend-plus/blob/master/migrations/1_init/up.sql#L113).

At Nhost we use the role `public` for public data that does not require login. So I think we should keep the "anonymous" terminology for this.

What we need to do is:

`/auth/anonymously/register` - register user with `anonymous` role, `display_name = Anonymous user`, `active = true`.
`/auth/anonymously/upgrade` - upgrade to regular user account. Should send email and password with the request. 

In HBPv1 we also had a `x-hasura-is-anonymous` boolean variable in the JWT token. I'm not sure if that's needed since the anonymous user has the default role `anonymous` which should be enough to set permission and security rules.

## Questions

- Should we add an `x-hasura-is-anonymous` claim? I think No
- Should we add the other default allowed user roles? I think Maybe. If Yes I think it's important to keep the `x-hasura-is-anonymous` claim to differentiate requests from a default allowed role from regular and anonymous users.
- Should we allow the same registration custom fields for Anonymous users? I think Yes but a bit unsure.
- Do we need something else for this to work?

**Comment by elitan** [comment] 2020-07-28 09:21
We could also add a CHECK constraint to not allow `public` in `auth.roles` to make sure the `public` role is only used for `HASURA_GRAPHQL_UNAUTHORIZED_ROLE`

**Comment by komninoschat** [comment] 2021-04-13 16:48
Duplicate of #475.

**Closed by komninoschat** 2021-04-13 16:48 UTC
